version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=secrets
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - ENCRYPTION_KEY=your_secret_key_here  # Ключ для шифрования
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=secrets
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: